site_name: 原神资料
site_url: https://gepsieh.github.io
site_description: 一些收集到的原神相关内容
site_author: suzu
use_directory_urls: false
nav:
- 公式收集:
  - 公式收集/常规伤害公式.md
  - 公式收集/月感电伤害公式.md
  - 公式收集/角色等级系数.md
- 杂项:
  - 杂项/参量质变仪.md
  - 杂项/抽卡概率.md
theme:
  name: readthedocs
  locale: zh_CN
extra_javascript:
- javascripts/extra.js
hooks:
- hooks/patch_lunr_zh.py
plugins:
- search:
    lang: zh
    min_search_length: 1
- git-revision-date-localized:
    type: datetime
    timezone: Asia/Shanghai
    locale: zh
    fallback_to_build_date: true
