site_name: 原神资料
site_url: https://gepsieh.github.io
site_description: 一些收集到的原神相关内容
site_author: suzu
use_directory_urls: false
markdown_extensions:
- pymdownx.arithmatex:
    generic: true

theme:
  name: readthedocs
  locale: zh_CN
  custom_dir: overrides
extra_javascript:
- javascripts/extra.js
- javascripts/mathjax.js
hooks:
- hooks/patch_lunr_zh.py
plugins:
- search:
    lang: zh
    min_search_length: 1
- git-revision-date-localized:
    type: datetime
    timezone: Asia/Shanghai
    locale: zh
    fallback_to_build_date: true
    enable_creation_date: true
    enable_git_follow: false
