name: deploy
on:
  push:
    branches:
      - main   # 你的源码分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install mkdocs         # 只装 mkdocs，自带 readthedocs 主题
      - run: mkdocs gh-deploy --force